### PR TITLE
Addition of an R-script to plot sd pipelines results

### PR DESCRIPTION
**Pull request by n400peanuts**
This is an R script that loads the files "pyannote_results.csv" and "pipelines_results.csv" (which contain the models' performance metrics) and plot them in a 2x2 plot.

### CODE REVIEW

**Review by maltelueken — CHANGES_REQUESTED** [review]
Looks really nice! One suggestion: The use of `=` and `<-` as well as `->` could be consistent. I would recommend only using `=` because it saves characters and avoids errors (like `- >`). I know it's not really "R style".

You could also include the plot iself (as pdf or png) in the PR.

**Review by maltelueken — COMMENTED** [review]
One other thing: You mentioned that the csv files are the output of the `compare_sd.ipynb` notebook. I cannot see any changes in this notebook that would produce these files. Could you also push these changes?

**Review by maltelueken — CHANGES_REQUESTED** [review]
Nice! One last thing: It might be nice to add a bit of information to the `pyannote_sd_compare.ipynb` notebook. Like what pipeline is presented in the notebook, what are the metrics and what is the conclusion. See the `compare_sd` notebook for example.

**Comment by maltelueken** [comment]
I looked into your description of the pipeline (which I believe is based on the Bredin 2020 paper) and noticed that this refers to the old version of pyanoote (1.0). For version 2.0, they use a different approach, which is not described in a paper yet:

1. They perform pyannotes speaker segmentation pipeline
2. They encode speaker segments as embeddings using a model by Speechbrain (ECAPA-TDNN)
3. They cluster segments based on the embedding vectors using agglomerative clustering by default.

This approach is basically the same as ours for the previous SD comparison. You can look at the code of the pipeline here: https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/pipelines/speaker_diarization.py

**Comment by n400peanuts** [comment]
>  But are we sure that it is the same as I am using? because I load the pipeline from huggingface: https://huggingface.co/pyannote/speaker-diarization

and they explicitly report the 2020 paper.

**Comment by maltelueken** [comment]
Looks great now!

**Review by maltelueken — APPROVED** [review]

**Pull request merged**
